ユースケース図/記述を作成
nishikawa1114/FaceEmotionSystem pull request #1
Opened 2020-10-20 05:21 UTC by nishikawa1114

ユースケース図/記述を作成しました。
内容の確認お願いします。(画面仕様についてはまだ作成していません)

* ユースケース図/記述のプレビュー
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/usecase/usecase/usecaseDescription.html
* ユースケース図/記述のソースコード
https://github.com/nishikawa1114/FaceEmotionSystem/blob/usecase/usecase/usecaseDescription.adoc

2020-10-21 02:25 UTC, wnakayama commented on usecase/usecaseDescription.adoc
> +. メッセージ01を表示する。
URLが不正もしくは空でメッセージ01を表示した後、ホーム画面に新しく画像は表示されないという認識で合っていますか?
メッセージ表示後に画像表示を行わない(事後条件を満たさない)のであれば、代替フローというより例外フローになるかと思います。

ここはちょっと紛らわしいポイントなので、代替フローと例外フローの違いを見直したうえで書き方を考えてみてください。

2020-10-21 02:42 UTC, wnakayama commented
基本フローのどのステップで代替フロー/例外フローに移行するのか明記しておきましょう。

例↓  (今回はAlt-1とフローに名前が付いているので とりあえず `→Alt-1`と書くだけでも十分だと思います。参考までに…)
![image](https://user-images.githubusercontent.com/54921025/96666243-af781400-1391-11eb-8e36-95339bc75d21.png)

2020-10-21 02:50 UTC, nishikawa1114 commented on usecase/usecaseDescription.adoc
> +. メッセージ01を表示する。
>URLが不正もしくは空でメッセージ01を表示した後、ホーム画面に新しく画像は表示されないという認識で合っていますか?

はい。URLが不正もしくは空の状態で「表示」ボタンを押した場合は新しい画像は表示されない想定です。

質問です。
代替フローと例外フローの違いは、
・事後条件を満たす→代替フロー
・事後条件を満たさない→例外フロー
という風に判断して問題ないですか？

2020-10-21 02:56 UTC, tamikura commented on usecase/usecaseDescription.adoc
> +image::home.png[home, 600]
URL入力欄が空だと「表示」ボタンを押下できない方が親切かと

2020-10-21 02:57 UTC, tamikura commented on usecase/usecaseDescription.adoc
> +image::home.png[home, 600]
分析ボタンは画像の下のほうがよいかと
（動線的に左上→右下が基本）

2020-10-21 02:59 UTC, wnakayama commented on usecase/usecaseDescription.adoc
> +. メッセージ01を表示する。
OKです。
ついでに、代替フローの場合は実行後に基本フローのどのステップに戻ってくるのかも書きましょう。

2020-10-21 04:41 UTC, iwanam reviewed
- ユースケース図だとServerという登場人物がいるけどユースケース記述に全く出てこないのはなぜでしょう？
- そもそもServerという名前だと一般的過ぎて、何者なのかわからなさそうな気も・・

2020-10-22 00:12 UTC, tatsuyaagawa requested changes

2020-10-22 00:12 UTC, tatsuyaagawa commented on usecase/usecaseDescription.adoc
> +. システムは画像の分析結果を表示する
分析結果のAPIがエラーのレスポンスを返してきたときはどうなりますか？

2020-10-22 01:03 UTC, nishikawa1114 commented
21日に頂いたレビューを踏まえ、以下の内容を変更しました。
確認お願いします。

- ユースケース図のアクター「Server」の名称を「表情分析システム」に変更。変更に伴いユースケース記述の内容も一部変更。
- ユースケース記述のURLが間違っていた場合のフローを例外フローに変更
- URLが未入力の場合表示ボタンを押下できない仕様に変更
- 画像が選択されていない場合、分析ボタンを押下できない仕様に変更
- 画面レイアウトのボタン配置を変更

* htmlプレビュー
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/usecase/usecase/usecaseDescription.html

2020-10-22 01:20 UTC, nishikawa1114 commented on usecase/usecaseDescription.adoc
> +. システムは画像の分析結果を表示する
APIからのレスポンスがエラーの場合、エラー画面を表示して「ホーム画面へ戻る」ボタンなどを用意して、ホーム画面に戻れる処理にしたいと思います。
問題ないでしょうか？

また、画像を表示する処理でもエラーが返ってくる場合が想定されるので、その場合も同じようにエラー画面を表示してホーム画面に戻る流れにする、というので問題ないですか？

2020-10-22 02:31 UTC, tatsuyaagawa commented on usecase/usecaseDescription.adoc
> +. システムは画像の分析結果を表示する
はい。記載してくれている流れで良いと思います

2020-10-22 05:52 UTC, tamikura approved these changes

2020-10-22 06:02 UTC, iwanam reviewed
ちょっと質問。
ここに書いている「表情分析システム」というのは自分でこれから作ろうとしているシステム？それとも、Face～APIとかいうのが提供しているところを想定している？

2020-10-22 06:06 UTC, nishikawa1114 commented
>ここに書いている「表情分析システム」というのは自分でこれから作ろうとしているシステム？それとも、Face～APIとかいうのが提供しているところを想定している？

「表情分析システム」はFace APIが提供している部分を想定しています。
※Face APIは画像に映っている人の表情から感情を分析して数値を返してくれるAPIです。

2020-10-22 06:08 UTC, nishikawa1114 commented
> > ここに書いている「表情分析システム」というのは自分でこれから作ろうとしているシステム？それとも、Face～APIとかいうのが提供しているところを想定している？
> 
> 「表情分析システム」はFace APIが提供している部分を想定しています。
> ※Face APIは画像に映っている人の表情から感情を分析して数値を返してくれるAPIです。

2020-10-22 06:41 UTC, iwanam commented
とすると、UC01で画像を表示しているのは表情分析システムであってる？

2020-10-22 07:09 UTC, nishikawa1114 commented
>とすると、UC01で画像を表示しているのは表情分析システムであってる？

確かに、表情分析システムは画像の表示はしないですね。
FaceAPIと自分が作ろうとしているシステムを明確に分離して考えられていなかったので、わかりにくくなってますね…
その場合、ユースケースは単に「システムは画像を表示する」のように書くのがよいですか？

(ちなみに、Asureの使用方法を確認すると、表情分析システム(※Face API)とは別のシステムに画像を保存するそうです。
その画像を受け取ってブラウザに表示して、FaceAPIに投げて分析するという想定。)

2020-10-22 07:16 UTC, iwanam commented
そうだね。
西川くんの作るシステムはどういうシナリオで動くのかというのが大事なので、あるユースケースは、ユーザ、西川くんのシステム、外部システムがどうかかわって何をするのか、というのを明確にするのが大事。

2020-10-22 08:14 UTC, wnakayama approved these changes

2020-10-23 02:42 UTC, nishikawa1114 commented
22日のレビューを踏まえ以下の修正を実施しました。
確認お願いします。
- 画像の取得および分析がエラーの場合のフローを追加
- エラー画面を追加。それに伴うメッセージの追加。
- ユースケース記述の一部の主語「表情分析システム」を「システム」に変更
- ユースケース記述「画像を分析する」の備考に分析結果に含まれる感情の種類を記載

* htmlプレビュー
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/usecase/usecase/usecaseDescription.html

2020-10-26 02:37 UTC, tatsuyaagawa approved these changes

2020-10-26 05:18 UTC, iwanam commented
アクターに「表情分析システム」がいるのにメインフローに出てこないのはおかしいですな。
例外フローでいきなり出てくるけど、その大本がメインにいるはず！

2020-10-26 05:30 UTC, nishikawa1114 commented
>アクターに「表情分析システム」がいるのにメインフローに出てこないのはおかしいですな。

ユースケース「画像を分析する」のメインフロー2と3の間に「表情分析システムはシステムに画像の分析結果を渡す」のフローを追加するのが良いでしょうか。
それとも、
「システムは表情分析システムに画像の分析を依頼する」
「表情分析システムはシステムに画像の分析結果を渡す」
のように、もっと細分化して記述すべきでしょうか？

2020-10-26 05:35 UTC, iwanam commented
そうねー。
少なくとも依頼する、が無いと分析システムがエラーになるパターンが発生しないような気がするよね。

2020-10-26 07:17 UTC, nishikawa1114 commented
指摘を踏まえ以下の修正を実施しました。

- ユースケース「画像を分析する」のメインフローに表情分析システムとの関連を追加記述

確認お願いします。

- htmlプレビュー
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/usecase/usecase/usecaseDescription.html

2020-10-26 07:19 UTC, iwanam approved these changes

2020-10-26 07:31 UTC, nishikawa1114 commented
マージします。
レビューありがとうございました！

2020-10-29 01:38 UTC, merged