API仕様書作成
nishikawa1114/FaceEmotionSystem pull request #10
Opened 2021-01-05 02:52 UTC by nishikawa1114

OJT課題で作成しているWebアプリケーションのAPI仕様書を作成しました。
指摘、修正点などの確認お願いします。

- 仕様書プレビュー(HTML)
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/api_specification/doc/api/api.html

**参考ドキュメント**
- 機能仕様所
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/main/doc/usecase/usecaseDescription.html

2021-01-05 05:03 UTC, tatsuyaagawa requested changes

2021-01-05 05:03 UTC, tatsuyaagawa commented on doc/api/api.adoc
> +|キー
レスポンスってここに記載されているオブジェクトの配列ですよね？
配列だとわかるように見直しをお願いします。

2021-01-05 05:03 UTC, tatsuyaagawa commented on doc/api/api.adoc
> +HTTP/1.1 400 Bad Request
ここは500？
https://github.com/nishikawa1114/FaceEmotionSystem/pull/10/files#diff-2751b4b1a9615fd33cd24ec7ec2e25ff27e8bb16fc9cee736dacfa1b70b0d84eR76

2021-01-05 06:44 UTC, SeigoKawamura requested changes

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +* url (string)
urlを必ず指定する必要がある場合は、必須と書いた方が親切です

```suggestion
* 必須
** url (string)
```

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|FaceId
型も追記してほしいです

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|BadGateway
Bad Gateway は502で、503はService Unavailable ですね
ただ、そもそもここのcodeはHTTPステータスコードのことではなくFaceAPIが独自に返すエラーコードみたいなので、503の場合はcodeを返す必要もないと思います。

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|パラメータが未入力、または不正な場合
顔検出ができなかった場合は400エラーですかね？

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|AzureFaceAPIからエラーが返却された場合
FaceAPIからのエラーは全て500エラーですか？

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +			}
"の位置がおかしいのと、:の後にスペースがないです。
それと、インデントが他と合っていないので合わせましょう。

2021-01-05 06:44 UTC, SeigoKawamura commented on doc/api/api.adoc
> +        "message": "Request body is invalid."
messageについての記載がないです。

2021-01-05 07:02 UTC, nishikawa1114 commented on doc/api/api.adoc
> +HTTP/1.1 400 Bad Request
500  Internal Server Error
ですね。FaceAPIからのエラーの場合の例だったので。
修正します。

2021-01-05 07:17 UTC, nishikawa1114 commented on doc/api/api.adoc
> +|パラメータが未入力、または不正な場合
顔検出ができなかった場合とは、分析した結果顔が検出できなかった場合でしょうか。
それとも、そもそも分析できなかったエラーの場合でしょうか。

前者の場合、分析は行えたが結果を取得できなかったとして400を返す想定でした。
(前半課題で作成したWebアプリケーションの動作は、顔が検出されず感情の分析結果が取得できなかった場合をエラー表示する設計としています)

後者の場合は、FaceAPIから何かしらのエラーが返却されるはずなので、外部サーバーに起因するエラーとして500を返す想定です。

2021-01-05 07:23 UTC, nishikawa1114 commented on doc/api/api.adoc
> +|AzureFaceAPIからエラーが返却された場合
外部サーバーに起因するエラーとして、このAPIからは500を返すつもりです。

FaceAPIから返却されるエラーに応じてこのAPIが返すエラーも場合分けしたほうがよいのでしょうか？(エラーによっては503などほかのステータスにするとか？)

2021-01-05 07:47 UTC, yhanba commented on doc/api/api.adoc
> +** 感情値
可能であれば、感情値の幅（0～1）を記載したほうが良いと思います。

Java向けのReferenceにてEmotionの定義を見つけたけど、ほかの言語でも同じかな…
https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cognitiveservices.vision.faceapi.models.emotion?view=azure-java-stable

2021-01-05 08:07 UTC, nishikawa1114 commented on doc/api/api.adoc
> +** 感情値
指摘ありがとうございます。追記します。

↓のドキュメントを見る限り、言語に関係なく[0,1]の間の数値をとると思われます。(すべての合計値が1になる) 
https://docs.microsoft.com/ja-jp/azure/cognitive-services/face/concepts/face-detection

2021-01-06 03:15 UTC, msebata approved these changes
半場さんと川村さんの指摘に対応すればOKです。

2021-01-06 03:15 UTC, msebata commented on doc/api/api.adoc
> +|FaceId
先頭の f は小文字では？

2021-01-06 04:32 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|requese body is invalid
```suggestion
|request body is invalid
```

2021-01-06 04:32 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|パラメータが未入力、または不正な場合
伝わりにくくててすみません、前者のつもりで質問しました。
400エラーにするのは良いですが、「パラメータが未入力、または不正な場合」とerrorの内容は分けた方が良いです。
「request body is invalid」というエラーの内容と「画像内に顔が検出されない場合」とで説明が合っていないためです。

2021-01-06 04:48 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|AzureFaceAPIからエラーが返却された場合
はい、分けた方が良いですね。
FaceAPIが400エラーを返す場合(例えば、画像のフォーマットが不正な場合や画像のサイズが小さすぎるor大きすぎる等)でも500エラーを返すのはよろしくないので。
上記の場合は400エラーを返すのが良いと思います。

2021-01-06 04:59 UTC, SeigoKawamura requested changes

2021-01-06 04:59 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|AzureFaceAPIからエラーが返却された場合
はい、分けた方が良いですね。
FaceAPIが400エラーを返す場合(例えば、画像のフォーマットが不正な場合や画像のサイズが小さすぎるor大きすぎる等)でも500エラーを返すのはよろしくないので。
500エラーはサーバー側で予期せぬエラーが発生した場合に返すものなので、上記のようなケースでは400エラーを返すのが良いと思います。

2021-01-06 04:59 UTC, SeigoKawamura commented on doc/api/api.adoc
> +}
失敗時の表と記載が合っていないです。
500の場合はerrorが"Face API response is error" となっています。
この辺りは後で変更が入ると思いますが、一応コメントしておきます。

2021-01-06 06:14 UTC, tatsuyaagawa approved these changes

2021-01-06 07:30 UTC, nishikawa1114 commented on doc/api/api.adoc
> +|AzureFaceAPIからエラーが返却された場合
ありがとうございます。
FaceAPIのエラーが400エラーの場合は、本APIも400エラーを返すようにします。

400以外の400番台のエラーの場合、(FaceAPI返すエラーは、401, 403, 408, 415, 429。[リファレンスより](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236))
429のみAPIのユーザーで対処できるリクエストの問題と考えられるので、429はそのままステータスを利用し、
それ以外のエラーの場合、500を返すという仕様で問題ないでしょうか？
それとも400番台のエラーはそのまま本APIのレスポンスのステータスとするのがよいでしょうか？

2021-01-06 08:12 UTC, yhanba approved these changes

2021-01-07 04:59 UTC, SeigoKawamura requested changes

2021-01-07 04:59 UTC, SeigoKawamura commented on doc/api/api.adoc
> +	}
ここのインデントは上と揃えてください。

2021-01-07 04:59 UTC, SeigoKawamura commented on doc/api/api.adoc
> +|request body is invalid
レスポンスサンプルでは最後にピリオドが付いていますが、ピリオドはつけますか？

それと、今更で申し訳ないですが、エラーコードとエラーメッセージを分けた方が良かったですね。
アプリからAPIを呼びだしてエラーが返ってきた際にエラーハンドリングをすると思いますが、現状、request body is invalidという文章で判定することになってしまうので、例えば、以下のように
```
{
  "error": "invalid_request",
  "description": "request body is invalid."
}
```
とか
```
{
  "code": 001,
  "description": "request body is invalid."
}
```
にして、エラーハンドリングする方がAPIを利用する側からしたら有難いかもしれないです。
↓他のサービスでのWebAPIのエラーをまとめている記事があったので、参考にしてみてください。
https://qiita.com/suin/items/f7ac4de914e9f3f35884

ただ、現状の仕様（エラーメッセージでハンドリングする）でも実装はできると思うので、対応するかどうかは任せます。

2021-01-07 05:48 UTC, nishikawa1114 commented on doc/api/api.adoc
> +|request body is invalid
>レスポンスサンプルでは最後にピリオドが付いていますが、ピリオドはつけますか？

ピリオドはつけます。(表にはピリオドがないけれどどちらが正しいのか、ということですかね？)
表にもピリオドつけておきます。

>それと、今更で申し訳ないですが、エラーコードとエラーメッセージを分けた方が良かったですね。
…

ご指摘ありがとうございます。
今回は現状の仕様のままとし、次回以降の設計の際に参考にさせていただきます。

2021-01-07 05:56 UTC, nishikawa1114 commented on doc/api/api.adoc
> +	}
ローカルのソースではインデントが揃っていますが、githubにpullしたファイルではインデントがずれてしまっているようです…
原因がわかりませんが修正ファイルをアップしなおしてみます。
(エクスポートしたHTMLファイルでもインデントはそろっているのでgithubの問題なのかな、と思います)

2021-01-07 06:41 UTC, nishikawa1114 commented on doc/api/api.adoc
> +	}
すみません。インデントにタブとスペースが混在してずれていたようでした。修正します。

2021-01-07 06:44 UTC, tatsuyaagawa requested changes
すいません。たまたまタイポ見つけてしまったので。。

2021-01-07 06:44 UTC, tatsuyaagawa commented on doc/api/old/api_01.adoc
> +        "detailes": {
```suggestion
        "details": {
```

2021-01-07 06:44 UTC, tatsuyaagawa commented on doc/api/api.adoc
> +	"detailes": {
```suggestion
	"details": {
```

2021-01-07 07:01 UTC, tatsuyaagawa approved these changes

2021-01-07 07:07 UTC, SeigoKawamura approved these changes

2021-01-14 01:59 UTC, merged