【OJT後半課題①】API クラス図・シーケンス図作成
nishikawa1114/FaceEmotionSystem pull request #11
Opened 2021-01-14 02:34 UTC by nishikawa1114

OJT後半課題①で作成するWebAPIのクラス図・シーケンス図を作成しました。
確認お願いします。

- クラス図
https://github.com/nishikawa1114/FaceEmotionSystem/blob/uml/out/doc/uml/classDiagApi/Face%20Emotion%20Analyser%20API.png
- シーケンス図
https://github.com/nishikawa1114/FaceEmotionSystem/blob/uml/out/doc/uml/seqDaigApi/FaceEmotionAnalyzer%20API.png

**参考**
- API仕様書
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/main/doc/api/api.html
- README
https://github.com/nishikawa1114/FaceEmotionSystem/blob/main/README.md

2021-01-14 02:59 UTC, wnakayama commented on doc/uml/seqDaigApi.pu
> +    FaceEmotionController -> ErrorController: 例外 InvalidRequestBodyExceptio をスロー
nが抜けてます
```suggestion
    FaceEmotionController -> ErrorController: 例外 InvalidRequestBodyException をスロー
```

2021-01-14 03:07 UTC, wnakayama commented
クラス図にもタイポがあります。レビュー依頼の前に確認で一度目を通しておくとよいですね。
* stataus → status
* AttrFibutes → Attributes
* happinessL → happiness
![image](https://user-images.githubusercontent.com/54921025/104539222-69fd7700-5660-11eb-9771-2ea428e6d274.png)

2021-01-14 04:13 UTC, nishikawa1114 commented
@wnakayama 
誤字脱字を修正しました。
確認不足でした。すみません。

2021-01-14 05:36 UTC, iwanam requested changes
- シーケンス図
  - ユーザに戻る矢印が2種類あるのはなぜ？
  - FaceEmotionControllerからErrorControllerに例外をスローしているけどどゆこと！？
  - 最初のAltは、メディアタイプを最初に持ってこなくて大丈夫？
  - 同様に、分析結果が取得できた、レスポンスがエラー、サーバーエラーみたいなのは並列になるかな？
  - ちなみにController内部でFaceAPI呼ぶ以外のめぼしい処理は無し？
- クラス図
  - ResponseとほかのXXXResponseの関係は？
  - パッケージでくくられていないものはどういう扱いでしょ？

2021-01-14 06:23 UTC, nishikawa1114 commented
>ユーザに戻る矢印が2種類あるのはなぜ？

すみません、間違いです。
全て非同期の処理として実装する予定ですので、非同期の矢印に統一します。

2021-01-14 06:39 UTC, nishikawa1114 commented
> 最初のAltは、メディアタイプを最初に持ってこなくて大丈夫？

エラーの場合を最初にはじいてからでないとよくないですね。
最初のAltを、メディアタイプ不正、パラメータ不正を最初に持っていきます。

> 同様に、分析結果が取得できた、レスポンスがエラー、サーバーエラーみたいなのは並列になるかな？

ここはすべてFaceAPIからのレスポンスで場合分けの判断をする想定なので、並列で場合分けを記述しようと思っています。

2021-01-14 06:40 UTC, nishikawa1114 commented
> ちなみにController内部でFaceAPI呼ぶ以外のめぼしい処理は無し？

はい。今回はFaceAPIの中継を行うAPIを作成しています。なのでFaceAPIを呼ぶ以外の主な処理はありません。

2021-01-14 06:44 UTC, nishikawa1114 commented
> ResponseとほかのXXXResponseの関係は？

「XXXResponse」はエラーの場合のレスポンスの型を定義しており、「Response」は「XXXResponse」を生成してXXXControllerに返す役割を持たせます。

2021-01-14 06:45 UTC, nishikawa1114 commented
> パッケージでくくられていないものはどういう扱いでしょ？

現在くくられていないものはすべてレスポンスに関係するクラスとなっており、Responseパッケージとする想定でした。のでResponseパッケージにまとめます。

2021-01-14 07:02 UTC, nishikawa1114 commented
> FaceEmotionControllerからErrorControllerに例外をスローしているけどどゆこと！？

FaceEmotionControllerで例外を発生させ、その場合のレスポンス内容の設定などの処理をErrorControllerで記述するのでこのような記述方法になっていました。
ここでは例外はユーザーにスローしていると考えるのが妥当ですかね？

ErrorControlerへの矢印は各例外発生時に呼び出されるメソッド名に変更し、
例外をスローの矢印はユーザーに伸ばす形に変更するがよいのでしょうか？

2021-01-14 07:28 UTC, tamikura commented
OKです

API仕様書はレビュー範囲じゃないので、指摘ではなく気になったところ

- エラーの値が文章、しかも中途半端な文章
  - request body is invalid. →先頭小文字。isあり
  - Face API server unavalable.　→先頭大文字。isがないので文法的におかしい
  - 文章にすると仕様変更に弱いので、エラーコード・エラーメッセージの２つに分けたほうが良い
  - faceAttributesの下にemotionが１つ。emotionはいるのか。。？ほかにも入る想定？

- クラス図・シーケンス図の書き方の学習としてはよいですが、意味があるのかは微妙なところ。。？
  - クラス図 → JSONフォーマットをほぼマッピング
  - シーケンス図 → ほとんどエラー処理の記載。。

2021-01-15 04:30 UTC, nishikawa1114 commented
@tamikura 
ご指摘ありがとうございます。
次回以降の課題で参考にさせていただきます。

>faceAttributesの下にemotionが１つ。emotionはいるのか。。？ほかにも入る想定？

これに関しては、FaceAPIからのレスポンスに形を合わせた結果になります。FaceAPIではfaceAttributesの下に入る分析結果がいくつかあります。今回はEmotion以外の分析結果を要求しないのでEmotion１つのままの予定です。

2021-01-15 06:15 UTC, nishikawa1114 commented
1/15 修正点
以下の修正を行いました。確認お願いします。

- クラス図
  - responseパッケージの追加
  - ErrorResponseクラスにメンバ追加

- シーケンス図
  - ユーザーへの矢印を非同期処理へ統一
  - 場合分けの順序を「メディアタイプ不正」「パラメータ不正」を最初に変更
  - 例外をスローの記述を削除。場合分けに起こるエラーの内容を記述し、処理フローを記述。


- クラス図
https://github.com/nishikawa1114/FaceEmotionSystem/blob/uml/out/doc/uml/classDiagApi/Face%20Emotion%20Analyser%20API.png

- シーケンス図
https://github.com/nishikawa1114/FaceEmotionSystem/blob/uml/out/doc/uml/seqDaigApi/FaceEmotionAnalyzer%20API.png

2021-01-15 06:54 UTC, tatsuyaagawa approved these changes
OKです
岩波さん指摘対応をお願いします

2021-01-15 06:58 UTC, wnakayama approved these changes
OKです。

2021-01-15 08:27 UTC, iwanam approved these changes
- ResponseはXXXResponseを作るためのクラスと定義するのはあまりよろしくないかなー

2021-01-19 08:21 UTC, merged