【OJT後半課題①】WebAPI実装
nishikawa1114/FaceEmotionSystem pull request #12
Opened 2021-01-22 01:55 UTC by nishikawa1114

2021-01-22 06:18 UTC, tatsuyaagawa requested changes
指摘が難しい。。

2021-01-22 06:18 UTC, tatsuyaagawa commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +				// ���ݐ���ɓ��삵�Ă��Ȃ��B
どう動かないかとか現状の解析結果とか現状わかっていることをPRにコメントとして書いておくと、もしかしたら誰か見てくれるかも

2021-01-22 06:18 UTC, tatsuyaagawa commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +				throw new FaceApiInvalidRequestException("Face API response is error.");
メッセージは別ファイルで管理するとよいと思います

2021-01-22 06:18 UTC, tatsuyaagawa commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/FaceApiErrorResponse.java
> +		private String message;
```suggestion
              @JsonProperty("error")
		private String message;
```
getterとかに `@JsonProperty`がついてますが、↑だと駄目なんですかね？
基本的なこと聞いていたらごめんなさい・・

2021-01-22 08:31 UTC, yutsunom requested changes

2021-01-22 08:31 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/Response.java
> +public class Response {
Response クラスは 一見するとErrorResonse やFaceApiErrorResponse  の基底クラスなので、今の(Factoryパターン)をやりたいなら名前変えたほうがいい

2021-01-22 08:31 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ErrorResponse.java
> +package com.face.response;
ResultData が成功時のレスポンスで、ErrorResponse 、FaceApiErrorResponse  はエラー時のレスポンス？
両方 model パッケージでは

2021-01-22 08:31 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/FaceApiErrorResponse.java
> +		private FaceApiError details;
命名が逆かなと。
親：FaceApiError 
子：FaceApiErrorResponse
に見える。

FaceApiError → FaceApiErrorResponseDetail などでは?

2021-01-22 08:31 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +		if (response.length == 0) {
念のためnull もチェックしたほうがよい

2021-01-22 08:31 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/Emotion.java
> +public class Emotion {
lombok 使っては（Getter、Setter 自動でつくるやつ）

2021-01-22 08:31 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/Param.java
> +public class Param {
命名が抽象的すぎる気が

2021-01-25 03:07 UTC, msebata requested changes

2021-01-25 03:07 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +		try {
try-catchは、例外(ここではHttpClientErrorException)が発生する可能性のあるところに絞り込んだほうがいいです。(全体を囲むとどこで例外が出るのかわかりにくいため)

2021-01-25 03:07 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/Param.java
> +	public String url;
privateにしましょう。

2021-01-25 03:07 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +					+ "?sv=2019-07-07&sr=c&si=myPolicyPS&sig=FkKJ4nXCiqzDYjbSaDfqli%2FnErPRTKrD%2BUQfH0MT3ac%3D");
クエリ文字列が謎です。この文字列の意味をコメントで書くなりしてくれると助かります。(自分以外の人がメンテナンスすることを考える)

2021-01-25 03:07 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/ErrorController.java
> +public class ErrorController extends ResponseEntityExceptionHandler {
名前を変えたほうがいいかも。 ErrorHandlerとか。

2021-01-25 03:07 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/ErrorController.java
> +
どこにもキャッチされなかった例外をハンドルするメソッドがあったほうがいいかも。(予期せぬエラーですが、ハンドリングしないとTomcatデフォルトのスタックトレースの画面が出てしまうと思うので)

2021-01-25 03:07 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +			if (url.url == null) {
空文字列でないかくらいはチェック追加してもいいかも。

2021-01-25 03:17 UTC, hiroshinhnakamura commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +					+ "?sv=2019-07-07&sr=c&si=myPolicyPS&sig=FkKJ4nXCiqzDYjbSaDfqli%2FnErPRTKrD%2BUQfH0MT3ac%3D");
javaの場合、URLのエンコード（エスケープ）を行うための標準API（java.net.URLEncoder）がありますが、使わない理由は何でしょう？

2021-01-25 03:24 UTC, hiroshinhnakamura commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +			String queryUrl = endPoint + "?detectionModel=detection_01&returnFaceAttributes=emotion&returnFaceId=true";
可読性に問題がないなら、クエリ文字列は定数としたほうが良いかと。
また、後々クエリを変更するような拡張を考えるなら、URIBuilder等でURIを生成したほうが間違えなくて済むと思います。（拡張しないなら必要なしですが）
https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/utils/URIBuilder.html

2021-01-25 04:57 UTC, nishikawa1114 commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +					+ "?sv=2019-07-07&sr=c&si=myPolicyPS&sig=FkKJ4nXCiqzDYjbSaDfqli%2FnErPRTKrD%2BUQfH0MT3ac%3D");
@msebata
@hiroshinhnakamura

このクエリ文字列は、今回用意しているサーバー上の画像を利用するために必要なクエリ文字列となっています(画像URLの一部であり、このプログラムとは関係ないものです)。
ソースコードにもコメント追記します。

クエリ文の生成はコーチャーにして頂いており、私はそれを利用しているだけですのでソースコード内でURLのエンコードは行っていないです。

2021-01-25 05:38 UTC, nishikawa1114 commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +			String queryUrl = endPoint + "?detectionModel=detection_01&returnFaceAttributes=emotion&returnFaceId=true";
@hirosinhnakamura
ご指摘ありがとうございます。
今のところ、今後もクエリの変更、拡張は考えていませんのでいまのままのソースコードで行こうかと思います。
今後の課題内容の中で、クエリの拡張をすることになった場合、参考にさせていただきます。

2021-01-25 06:25 UTC, nishikawa1114 commented
1/25日　修正
以下の修正を実施しました。
確認お願いします。

- エラーメッセージ管理のクラスの追加
- try-chatch分の範囲の変更
- リクエストパラメータの空文字判定追加
- FaceAPIからのレスポンスのnullチェック追加
- その他の(どこにもキャッチされなかった)エラーをハンドリングする例外処理を追加
- 変数、クラス名の変更

2021-01-25 06:28 UTC, nishikawa1114 commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/Emotion.java
> +public class Emotion {
@yutsunom
ご指摘ありがとうございます。
ご指摘頂いたのにすみませんが、時間の都合上、
今回は今のままのソースコードとし、次回以降の課題の中で参考にさせていただきます。

2021-01-25 08:42 UTC, hiroshinhnakamura approved these changes

2021-01-25 09:01 UTC, msebata approved these changes

2021-01-26 04:07 UTC, tatsuyaagawa approved these changes

2021-01-26 08:34 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/Param.java
> +public class Param {
ImageInfo に変えたのですね。了解です

2021-01-26 08:35 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/Emotion.java
> +public class Emotion {
了解です

2021-01-26 08:36 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +		if (response.length == 0) {
変わったの確認しました

2021-01-26 08:36 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/FaceApiErrorResponse.java
> +		private FaceApiError details;
確認しました

2021-01-26 08:39 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ErrorResponse.java
> +package com.face.response;
確認しました

2021-01-26 08:39 UTC, yutsunom commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/Response.java
> +public class Response {
確認しました

2021-01-26 08:40 UTC, yutsunom approved these changes
余裕があればクラス図も更新しておいてください

2021-01-27 08:37 UTC, merged