【OJTか】
nishikawa1114/FaceEmotionSystem pull request #13
Opened 2021-01-28 03:11 UTC by nishikawa1114

2021-01-28 04:51 UTC, tatsuyaagawa requested changes
Face APIから400, 429以外が返ってきた場合のテストも追加お願いします

2021-01-28 04:51 UTC, tatsuyaagawa commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/controller/FaceEmotionController.java
> +    private RestTemplate restTemplate;
ここだけ微妙にスペースになっているのが気になるのでタブかスペースにそろえてください

2021-01-28 04:51 UTC, tatsuyaagawa commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/controller/FaceEmotionControllerTest.java
> +				.andExpect(status().isOk());
レスポンスボディはチェックしない？
あと２人以上の顔が検出されたパターンとか

2021-01-28 05:03 UTC, msebata requested changes
レビュアじゃないけどコメントさせてもらいました。

2021-01-28 05:03 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/controller/FaceEmotionControllerTest.java
> +		mockMvc.perform(MockMvcRequestBuilders.post("/face/emotion").contentType(MediaType.APPLICATION_JSON)
(レビュアじゃないけど)
これは実際にFaceAPIをたたいてるように見えます。
単体テストなので、400のテストのように MockRestServiceServer  を使って通信をモックにしたほうが良いと思います。

2021-01-28 05:03 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/controller/FaceEmotionControllerTest.java
> +	@Autowired
mockMvcにAutowiredは要らないです。SpringのDIコンテナではなくsetup()で生成しているので。

2021-01-28 08:00 UTC, iwanam requested changes

2021-01-28 08:00 UTC, iwanam commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +	// ���X�|���X {"error":"test error"} ����
これって期待値とテスト内容が違いません？

2021-01-28 08:12 UTC, nishikawa1114 commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +	// ���X�|���X {"error":"test error"} ����
@iwanam

ErrorResponse response = ResponseFactory.createErrorResponse(ex);
の戻り値が{"error":"test error"}というErrorResponse型のオブジェクトを想定していて、
実行して返ってきたオブジェクトresponseのキー"error"の値が"test error"になっていることを確認しているのですが、期待値とテスト内容に齟齬があるでしょうか？

2021-01-28 08:23 UTC, nishikawa1114 commented
1/28日修正点

- インデントの修正
- FaceAPIからのエラーが400、429以外の場合を追加
- 2人以上の分析結果の場合を追加
- FaceAPIとの通信をすべてモックを使用するように変更
- @BeforによるMockMvcの初期化処理の削除(@AutoConfigureMockMvcが自動で行ってくれるため必要ない)

2021-01-28 23:58 UTC, iwanam commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +	// ���X�|���X {"error":"test error"} ����
>レスポンスが{"error":"test error"}を期待

ならレスポンスと上記文字列との比較があってしかるべきだと思うんですが、今回はそれを処理した結果のResponseのErrorがtest errorであることを期待しているのでは？
もしくはNotDetectedExceptionからResponseを生成した場合、そのErrorMessageがErrorからとれることか。

2021-01-29 01:03 UTC, nishikawa1114 commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +	// ���X�|���X {"error":"test error"} ����
@iwanam

> 今回はそれを処理した結果のResponseのErrorがtest errorであることを期待しているのでは？

そのような想定でした。であれば、
「ErrorResponseが生成され、errorの値が"test error"を期待」
のように書くのであれば、テスト内容と期待値が一致するでしょうか。

2021-01-29 01:55 UTC, iwanam commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +	// ���X�|���X {"error":"test error"} ����
そうね。要するにコメントってやつはドキュメントと同じで、「読み手」にわかりやすいか、が重要です。
今回はメッセージだけが書いてあるけど、それが処理の中でどう変換されるかがわかっている前提のが隠れているのでそれを知らないor仕様が変わったときに他人が何を直すかがわかりにくいかもしれない
実際のシステムなら10項目20項目JSONに含まれることも多いので、もしそれが期待値として書いてあって、メッセージの比較assertだけがテストに書いてあったら、何をやっているかわかりにくいかもしれないよね。

2021-01-29 02:35 UTC, msebata approved these changes
今回はFaceAPIのレスポンスをそのままControllerのレスポンスにしているので、あまり意味はないですが、レスポンスボディの検証の仕方も確認しておいてください。(エラーレスポンスは自作なので一つぐらいやってもいいと思う)

2021-01-29 02:43 UTC, nishikawa1114 commented
1/29修正点

- テストコメントの修正

2021-01-29 02:59 UTC, iwanam approved these changes

2021-01-29 08:03 UTC, tatsuyaagawa approved these changes

2021-02-02 00:26 UTC, merged