【OJT後半課題】機能仕様書　修正
nishikawa1114/FaceEmotionSystem pull request #14
Opened 2021-02-02 07:13 UTC by nishikawa1114

2021-02-03 04:40 UTC, tatsuyaagawa requested changes
細かいところ一か所だけ

2021-02-03 04:40 UTC, tatsuyaagawa commented on doc/functional_specifications/usecaseDescription.adoc
> +. システムは画像に映る人すべての分析結果を表示する
```suggestion
. システムは画像の分析結果を表示する。分析結果に複数人のデータが含まれる場合にはすべての結果を表示する
```
とかかなと思いました、
細かいですが、画像に映っていてもFaceAPI側から帰ってこないケースなんかもありそうなので。

2021-02-03 07:29 UTC, nishikawa1114 commented
2/3　修正点
画面仕様および指摘頂いたユーズケース記述の説明を修正、追加しています。
確認お願いします。

2021-02-04 04:15 UTC, tatsuyaagawa commented on doc/functional_specifications/usecaseDescription.adoc
> +画像に複数の人が映っている場合、分析結果は縦に並んで全員分表示する。
ここは表領域の説明というより分析結果画面全体の説明な気がします

2021-02-04 04:46 UTC, nishikawa1114 commented on doc/functional_specifications/usecaseDescription.adoc
> +画像に複数の人が映っている場合、分析結果は縦に並んで全員分表示する。
確かにそうですね。
現在は画像、グラフ、表ごとに説明欄を設けている状態ですが、表に「分析結果表示領域」の行を追加して、記述するのがよいでしょうか？
それとも、表はそのままで、表の上などに記述するほうがよいでしょうか？

2021-02-04 06:59 UTC, nishikawa1114 commented
2/4　修正点
- 複数の分析結果の表示方法の説明箇所を移動
- 画像の表示上限について記載
- 分析人数の上限について記載

2021-02-04 07:01 UTC, tatsuyaagawa approved these changes

2021-02-04 07:36 UTC, merged