[OJT課題イテレーション2]ソースコード・単体テスト　作成
nishikawa1114/FaceEmotionSystem pull request #16
Opened 2021-02-16 01:20 UTC by nishikawa1114

**[OJT課題イテレーション2]ソースコード・単体テスト　作成**

OJT課題で作成している画像に映る表情分析するwebアプリケーションに、複数人写る画像の分析結果の表示機能を追加しました。

**画面キャプチャ**
- ホーム画面
![image](https://user-images.githubusercontent.com/69957397/108006961-1eaffd00-7040-11eb-8332-116a0f9f5cc7.png)
- 分析結果画面
![image](https://user-images.githubusercontent.com/69957397/108007042-50c15f00-7040-11eb-85f3-4e61cab3812c.png)

![image](https://user-images.githubusercontent.com/69957397/108007051-59b23080-7040-11eb-9090-d84404e41e5b.png)

2021-02-16 02:18 UTC, iwanam requested changes
ちなみにグループの画像は1パターンしかない？
しかも全部ハピネス？

2021-02-16 02:18 UTC, iwanam commented on src/my-app/src/AnalyzeDetail.tsx
> +            const cnvs = document.getElementById('canvas' + this.props.id) as HTMLCanvasElement;
この辺りは好みなんだけど、変数名はわかりやすいことが重要なのでさほど短縮されない形で省略するのは避けたほうがいいかもしれないですな。
img、ctx、propsは市民権を得ている短縮だし、誤解を生みづらいけど、cnvsの場合は宣言箇所を見てからじゃないとほかのコードが読みづらくなるかもしれない。
20-30年前は、なるべく変数名はわかる範囲で短くというルールが当たり前にあったんだけど、いまは画面もでかいしメモリもでかいし、読みやすさ重視でいいと思う（もちろん長すぎる名前は逆に読みづらいけどね）

2021-02-16 02:18 UTC, iwanam commented on src/my-app/src/AnalyzeDetail.tsx
> +                    20, 20, 200, 100);
こういう長い計算式があるところは、コメントに概要が書いてあると読みやすい。
マジックナンバーも取り立てて定数にするほどでもない場合はコメントを頼りにできるしね。

2021-02-16 02:18 UTC, iwanam commented on src/my-app/src/AnalyzeResult.tsx
> +    getDate = (str: string) => {
もしもurl前提で処理を書いているのであれば、引数の名前もurlがいいと思うんだよね。
そうでなくて汎用的に書いたのであればコメントをそうしたほうがわかりやすい。
実際の製品にする場合は、本当に想定したURLなのかというチェックがどこかで必要になるのは留め置くといいかも。

2021-02-16 02:36 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeDetail.tsx
> +            const cnvs = document.getElementById('canvas' + this.props.id) as HTMLCanvasElement;
ありがとうございます。

propsはReactで定められた単語のため変更できませんが、それ以外の単語は省略なしのスペルに変更します。

2021-02-16 02:36 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeDetail.tsx
> +                    20, 20, 200, 100);
計算式の理由をコメントにて追記します。

2021-02-16 02:37 UTC, tatsuyaagawa requested changes

2021-02-16 02:37 UTC, tatsuyaagawa commented on src/my-app/src/Analyzer.ts
> +                const resuleData = data;
レビュー対象外なので対応しなくても良いですが、一時変数に入れずそのままretrurn data;で良いと思います

2021-02-16 02:37 UTC, tatsuyaagawa commented on src/my-app/src/AnalyzeResult.tsx
> +        const strDate = String(str.match(/\d{4}\/\d{2}\/\d{2}/));
日付取れなかった場合"null"になってしまうみたいですが、チェックは不要ですか？
コメントに追加で期待するURLとか書いてあると良いかなと思います

2021-02-16 02:37 UTC, tatsuyaagawa commented on src/my-app/src/__tests__/AnalyzeResult.test.tsx
> +// 複数人映る画像の分析結果が表示できているかテスト
11人以上データがあっても10人しか表示されないことのテストも追加お願いします

2021-02-16 02:39 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeResult.tsx
> +    getDate = (str: string) => {
URL前提で処理を書いています。
引数の名前もurlに変更します。

>実際の製品にする場合は、本当に想定したURLなのかというチェックがどこかで必要になるのは留め置くといいかも。

ありがとうございます。想定したURLかどうかのチェックについても今後の課題で取り入れられるか検討いたします。

2021-02-16 02:40 UTC, nishikawa1114 commented
@iwanam 
>ちなみにグループの画像は1パターンしかない？
しかも全部ハピネス？

現在サンプルとして用意しているのは今利用している一枚のみになります。複数人の表示ができているかの確認ができればよいと考えていたため)。

テスト用に、表情や人数にもう少し種類を増やすために画像を探しているため、結合テスト時にはもう少しバリエーションのある画像でのテストができると思います。

2021-02-16 02:50 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeResult.tsx
> +        const strDate = String(str.match(/\d{4}\/\d{2}\/\d{2}/));
現在は想定するURLかどうか、日付が取得できたかなどのチェックは行えていません。
日付がnullとなる場合は「」（空文字）を返して表示するように、まずは対応いたします(null表示のままはよくないので…)。

期待するurlについてコメントで追記します。

2021-02-16 03:51 UTC, SeigoKawamura requested changes

2021-02-16 03:51 UTC, SeigoKawamura commented on src/my-app/src/AnalyzeDetail.tsx
> +                    20, 20, 200, 100);
実際のコード規約がどうなっているのかは分からないですが、ここの引数は全て改行した方が分かりやすいかと思います。
それと、最後の引数の200,100は表示する幅と高さだと思うのですが、PRの説明で貼ってもらった画像は正方形で表示されているのは何でなのでしょうかね？

2021-02-16 03:51 UTC, SeigoKawamura commented on src/my-app/src/AnalyzeResult.tsx
> +        const temp: string = String(str.split('images/').pop());
期待するURLがどういうものかは分からないですが、 `*/images/images/*` みたいなURLだと上手くいかないと思います。
また、image/下に不正な文字列が入力された場合などの対策は問題ないですか？

2021-02-16 04:25 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeDetail.tsx
> +                    20, 20, 200, 100);
>実際のコード規約がどうなっているのかは分からないですが、ここの引数は全て改行した方が分かりやすいかと思います

改行します。

>それと、最後の引数の200,100は表示する幅と高さだと思うのですが、PRの説明で貼ってもらった画像は正方形で表示されているのは何でなのでしょうかね？

はい、表示する幅と高さです。
すみません、私も原因がどこにあるのかをわかっていない状態です。100,100だと長方形になってしまうので、とりあえず正方形で表示される指定法をしているといった状況です。

2021-02-16 07:03 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeResult.tsx
> +        const temp: string = String(str.split('images/').pop());
期待するURLとしては
　~~~/images/(ユーザー名)/(年)/(月)/(日)/(画像ファイル名)/~~
のような形です。

>*/images/images/* みたいなURLだと上手くいかないと思います。

そうですね。その場合は正しくユーザー名を取得できません。
images/下に不正な文字列が入力された場合の対策は現在行えていません。

images/~~~/(年)/(月)/(日)/で囲われた部分(~~~)をユーザー名として取得するように対策します。

2021-02-16 07:51 UTC, nishikawa1114 commented
2/16修正点

- 変数名の省略形を省略なしに変更
- 分析結果の画像表示部分の計算式のソースコードにコメント追記
- getName(), getDate()関数の引数名の変更
- getDate()関数を日付が取得できない場合「-」を返すように変更
- getName()関数の引数のurl不正な場合に「-」を返すように変更
- ソースコードの整形

確認お願いします

2021-02-16 07:56 UTC, iwanam commented on src/my-app/src/AnalyzeDetail.tsx
> +            // 画像から分析滝対象の人物の顔を切り取って表示する
滝！？

2021-02-16 07:58 UTC, iwanam commented on src/my-app/src/AnalyzeResult.tsx
> +        if (tmp === "null") { // images/~~ の後にユーザー名が来ることを想定しているため"images/"を確認
何となくこうなった経緯はわかるけど、それでもnullは特別な値なのでこの形はあまりよろしくないかなー

2021-02-16 07:58 UTC, iwanam approved these changes

2021-02-16 07:58 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeDetail.tsx
> +            // 画像から分析滝対象の人物の顔を切り取って表示する
すみません。気づきませんでした。
修正します。

2021-02-16 07:59 UTC, tatsuyaagawa commented on src/my-app/src/AnalyzeResult.tsx
> +        }
```
if ( !url.match(regex) ) {
     return "-";
}
```
こうしたい気がしますが、とりあえずそのままでも良いかな

2021-02-16 09:26 UTC, yhanba commented on src/my-app/src/AnalyzeResult.tsx
> +    // utlの画像を分析する
utl?

2021-02-16 09:36 UTC, yhanba commented on src/my-app/src/__tests__/Analyzer.test.tsx
> +  // 一人が映った画像の分析結果を受け取るテスト
今回は静止画を扱っているので、写る　が正しいですかね

2021-02-16 09:38 UTC, yhanba commented on src/my-app/src/__tests__/Analyzer.test.tsx
> +  // 複数人移った画像の分析結果を受け取るテスト
複数人移った→写った

2021-02-16 09:45 UTC, yhanba commented on src/my-app/src/AnalyzeResult.tsx
> +        const regex = /(images){1}\/.*\d{4}\/\d{2}\/\d{2}/;
単にユーザー名を取得するだけであれば、後ろの年月日を意味する、d{4}\/\d{2}\/\d{2}の部分はいらないと思います。
もしも、URLにパターンがないのであれば、URLのバリデーション処理はgetDateとgetNameで共通にしてしまっても良いかもしれません。

2021-02-16 09:50 UTC, yhanba commented on src/my-app/src/AnalyzeResult.tsx
> +        const MAX_LENGTH = 10;
MAX_LENGTHは、もう少し具体的に何の最大長なのか分かるように変数名を付けた方がよいと思います。
データの長さやタイムアウト時間とかを意味する定数は経験上色々なパターンが増えていくので、具体的な名前をうけておくと今後の修正で同じような定義が増えた際に、区別しやすくなります。

2021-02-17 00:03 UTC, SeigoKawamura approved these changes

2021-02-17 01:42 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeResult.tsx
> +        const regex = /(images){1}\/.*\d{4}\/\d{2}\/\d{2}/;
@yhanba

今回はurlは基本的に想定したurlが来ること前提ですが、画像のURLであればなんでも利用できてしまうため想定しない値が名前や日付として表示されないようにバリデーション処理を用意しています。

共通にというのは、getNameで行っているようなバリデーションを行う関数を用意して、それをgetNameとgetDateの両方で利用する、ということでしょうか（あってますか？）。
そのように修正します。

2021-02-17 02:08 UTC, nishikawa1114 commented
2/17修正点

- 変数名修正
- urlのバリデーション処理を関数化
- 誤字修正

2021-02-17 04:14 UTC, yhanba commented on src/my-app/src/AnalyzeResult.tsx
> +        const regex = /(images){1}\/.*\d{4}\/\d{2}\/\d{2}/;
共通にというので私がイメージしたのは以下の2つの修正方法です。
（案２は案１を実施しない場合の妥協案の認識です）

案１：getNameで行っているようなバリデーションを行う関数を用意して、それをgetNameとgetDateの両方で利用する
案２：getNameで使っているregex(/(images){1}\/.*\d{4}\/\d{2}\/\d{2}/)を定数化してgetDateとgetNameで利用する
　
案１の方法で修正していただけるということでれば、意図とあっているので大丈夫です。

2021-02-17 05:48 UTC, yhanba approved these changes

2021-02-17 08:10 UTC, tatsuyaagawa approved these changes

2021-02-24 05:36 UTC, merged