【OJT後半課題3】機能仕様書　修正
nishikawa1114/FaceEmotionSystem pull request #18
Opened 2021-03-02 04:06 UTC by nishikawa1114

**【OJT後半課題3】機能仕様書　修正**

OJT課題で作成している感情分析アプリケーションに、画像に写る全員の感情の平均値を表示する機能を追加する記述を加えました。
確認お願いします。

- [機能仕様書プレビュー](http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/specificatioin/doc/functional_specifications/function_specification.html)

- 追記変更箇所
  - 分析画面の画面仕様のイメージ図と説明の修正
  
![image](https://user-images.githubusercontent.com/69957397/109589871-5fcf0380-7b4e-11eb-9816-399c0ba6de9c.png)

  - UC02のユースケース記述 
![image](https://user-images.githubusercontent.com/69957397/109589915-6d848900-7b4e-11eb-9afc-41d07e83e26c.png)

2021-03-02 04:59 UTC, tatsuyaagawa requested changes

2021-03-02 04:59 UTC, tatsuyaagawa commented on doc/functional_specifications/usecaseDescription.adoc
> +// * 分析可能人数上限：10人
l.100-l.103はソースコードのコメントとして残しておく必要はなくて、githubのPR内のコメントとして書いておくくらいで良いかと思います

2021-03-02 04:59 UTC, tatsuyaagawa commented on doc/functional_specifications/usecaseDescription.adoc
> +|画像に写る全員の感情の平均値を表示する。
一人の場合も表示する？

2021-03-02 05:01 UTC, nishikawa1114 commented on doc/functional_specifications/usecaseDescription.adoc
> +|画像に写る全員の感情の平均値を表示する。
1人の場合は平均値の表示は行いません。
複数人の場合のみ表示する記述に修正します。

2021-03-02 05:10 UTC, wnakayama commented
(今回の修正箇所とは関係ないですが)「負荷」→「不可」

![image](https://user-images.githubusercontent.com/54921025/109600689-d543cf80-7b60-11eb-83a0-1b47ad03f2b9.png)

2021-03-02 05:25 UTC, wnakayama commented
分析結果画面のサンプルと説明ですが、「領域」については番号を振るだけでなく対象の範囲がどこまでなのか赤枠で囲んで示すなどの工夫が欲しいです。  
今回で言うと⑤や⑥がどこまでを指すのかもう少し分かりやすくなると良いかなと思います。

2021-03-02 06:23 UTC, nishikawa1114 commented
3/2 修正点

- 画面仕様サンプル図に番号が示す領域の枠線を追加
- 画面仕様説明に複数人写る画像でのみ平均値を表示する旨追記
- 誤字修正
- 不要コメント削除

2021-03-03 02:26 UTC, tatsuyaagawa approved these changes

2021-03-03 02:43 UTC, wnakayama approved these changes

2021-03-03 05:18 UTC, msebata approved these changes

2021-03-04 02:56 UTC, merged