【OJT後半課題3】API仕様書 修正
nishikawa1114/FaceEmotionSystem pull request #19
Opened 2021-03-03 05:00 UTC by nishikawa1114

3/4 修正点2
- 感情値の有効桁数について明記
  - 平均値では計算過程で無限小数になる可能性を考慮して３桁で丸める
  - FaceAPIからの返却値はそのまま利用するため有効桁数定義しない
- 誤字修正 

3/4 修正点
- レスポンスの型名修正
- レスポンス説明文の修正
- レスポンスサンプルの１人の場合のサンプル削除
- 参考文献の項目を追加
- 誤字修正

[API仕様書プレビュー](http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/api/doc/api/api.html)

---

**【OJT後半課題3】API仕様書 修正** 

OJT課題で作成している感情分析アプリケーションで使用するAPIの機能に、分析結果と一緒に感情の平均値も返却するように変更を行います。
API仕様書の修正を行い、
APIのレスポンスのオブジェクトの中に分析データとは別に平均値のデータを追加して返却するように変更しています。

追加されたAPI仕様について、文章の書き方にについてなどの確認お願いします。

- API仕様書プレビュー
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/api/doc/api/api.html

- 変更前のAPI仕様書プレビュー
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/api/doc/api/api01.html

- 変更箇所(スクショ)
  - 説明文
  ![image](https://user-images.githubusercontent.com/69957397/109754713-e4da1b80-7c27-11eb-93c9-1d552ba47082.png)
 
  - レスポンス説明
![image](https://user-images.githubusercontent.com/69957397/109754013-a001b500-7c26-11eb-93f7-6da2bcfd07dd.png)
  - レスポンスサンプル(分析結果が1人)
  ![image](https://user-images.githubusercontent.com/69957397/109754057-ba3b9300-7c26-11eb-94b0-f29d440e839a.png)
  - レスポンスサンプル(分析結果が2人)
  ![image](https://user-images.githubusercontent.com/69957397/109754083-c45d9180-7c26-11eb-9395-a38eb5e42737.png)

2021-03-03 06:39 UTC, iwanam requested changes
サンプルがちゃんと更新してあったりデータにバラエティがあるのはいいと思います。

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
> +|total(int)
直すほどではないけど、型は別セルにしたほうが見やすいかも？

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
>  ** 200
今回の修正とは違うけど、API仕様にただ200と書いてあるとわかりづらいかも

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
> +** surprise (double)
今回は外部APIを利用しているからアレだけど、このあたりも一言説明があるといいね。

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
> +** neutral (double)
double型ってどういう定義が見ている人に伝わるかな？

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
箇条書きにする場合、併記されたものは同じグループというくくりになるので、ここは書き方を工夫したほうがいいかも

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
> +|顔の属性
日本語的な感覚だけど、個人的には顔というより表情という言葉のほうが真意がつたわるかなーと

2021-03-03 06:39 UTC, iwanam commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
ちなみにこの書き方って数学の閉区間を使って書いた感じです？
好みとしては小数なら小数で書きたい感じもしなくもないかなー

2021-03-03 06:53 UTC, yutsunom requested changes

2021-03-03 06:53 UTC, yutsunom commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
有効桁数が気になりました

2021-03-03 06:53 UTC, yutsunom commented on doc/api/api.adoc
> +* 分析人数が一人の場合
個人的には、2人の例があれば、１人の例は不要かなと

2021-03-03 06:53 UTC, yutsunom commented on doc/api/api.adoc
> +* 分析人数が2人以上の場合
2人以上というか、2人の例では
1人と2人以上で差があるとすれば、どう違うんでしたっけ（ぱっと見わからなかった）

2021-03-03 06:53 UTC, yutsunom commented on doc/api/api.html
>  <meta charset="UTF-8">
htmlファイルがここの階層で成果物管理されてるのは間違ってる気がします。(push不要だと思います。)ビルドすることで再現可能なため。
もし特別な意図があるなら構いませんが。阿川さんに確認してみてください。

2021-03-03 07:17 UTC, nishikawa1114 commented on doc/api/api.adoc
> +|total(int)
ご指摘ありがとうございます。今後参考にします。
直すほどではない、ということなので今回はそのままとしたいと思います。

2021-03-03 07:18 UTC, nishikawa1114 commented on doc/api/api.adoc
> +** surprise (double)
@iwanam
説明、というのは具体的にどういうものを想定しているのでしょうか？例えば、

neutral (double)：中立

のように、各項目がなんの感情を表しているのかの説明を書いたほうがよいということでしょうか？

2021-03-03 07:19 UTC, nishikawa1114 commented on doc/api/api.adoc
> +** neutral (double)
@iwanam

ここではjavaの型名で書いてました。
double ではなく「実数値」などのように日本語で書いたほうが良いということでしょうか？
そうなるとほかの型名も整数値や文字列のように修正したほうが良いということですか？

2021-03-03 07:20 UTC, nishikawa1114 commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
@iwanam

>箇条書きにする場合、併記されたものは同じグループというくくりになるので、ここは書き方を工夫したほうがいいかも

「emotion (Object) :  感情の強さ。[0,1]の間の数値。」

のように修正しようと思います。

>ちなみにこの書き方って数学の閉区間を使って書いた感じです？
好みとしては小数なら小数で書きたい感じもしなくもないかなー

はい。閉区間で書きました。
少数なら少数で、というのはどういうことでしょうか？
「0.0~1.0の間の実数値」
のように書く、ということですか？

2021-03-03 07:26 UTC, nishikawa1114 commented on doc/api/api.adoc
> +|顔の属性
@iwanam

ここは、外部利用しているFaceAPIのfaceAttributesオブジェクトに含めることができる情報が、感情以外にも性別、眼鏡、髪など、様々あり、それを考慮すると「顔の属性」とするのが良いかなと思っています。

ただ、今回は感情値以外は利用しないので、その場合は「表情の属性」のほうが確かに伝わりやすいかなとも感じました。
伝わりやすさ優先で「表情の属性」と修正します。

2021-03-03 07:31 UTC, iwanam commented on doc/api/api.adoc
> +** surprise (double)
Yes。その属性の意味は何か？というやつですね。
英単語なんだから理解しろよ、というのも通じないことはあるのと、場合によってはそのものの意味じゃなかったりしますしねぇ

2021-03-03 07:32 UTC, hiroshinhnakamura commented on doc/api/api.adoc
> +** neutral (double)
横からですが、JSONのレスポンスなのでデータ型はJSONの形式（string, number, object, array, etc.）に沿うべきでは？

2021-03-03 07:32 UTC, iwanam commented on doc/api/api.adoc
> +** neutral (double)
伝わるかどうか、かな。
例えばJavaの仕様書だったらそれでいいと思うし、言語によってはNumberが整数実数を含む場合もあるし。
誰にどういう形で見られるかというのが想定できていればいいと思います。

2021-03-03 07:34 UTC, iwanam commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
そうですね。[0,1]だと0-1という感じがして、[0.0,1.0]なら小数感がでるかなーと
どっちでもいいっちゃーいいと思うし、値域の書き方がどっちだったのか覚えてないんですけどねー。

2021-03-03 07:34 UTC, iwanam commented on doc/api/api.adoc
> +|顔の属性
それだけ主張できるならOK！

2021-03-03 07:35 UTC, nishikawa1114 commented on doc/api/api.adoc
> +* 分析人数が2人以上の場合
@yutsunom

1人と2人で差はないです。配列"person"の中身が1人分か2人分かの違いだけです。

2021-03-03 07:37 UTC, nishikawa1114 commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
@yutsunom

外部利用しているFaceAPIのドキュメントでは、有効桁数に関する記述が見つけられませんでした。
そうではなくこのAPIの仕様として、有効桁数を定めてそれ以下のけたは丸める等するようにしたほうがよいということでしょうか？

2021-03-03 07:39 UTC, nishikawa1114 commented on doc/api/api.adoc
> +* 分析人数が一人の場合
@utsunomiy

確かに見にくく、冗長な感じですね。
2人分のサンプルのみに修正します。

2021-03-03 07:44 UTC, nishikawa1114 commented on doc/api/api.adoc
> +** neutral (double)
>JSONのレスポンスなのでデータ型はJSONの形式（string, number, object, array, etc.）に沿うべきでは？

なるほど、そうですね。
今回は型名はJOSN形式に合わせてnumberとし、日本語の説明として整数、実数など追記して説明するということにしたいと思います。

2021-03-03 07:47 UTC, hiroshinhnakamura commented
今回の変更点への指摘ではないので修正しなくても良いですが、Azure Face API仕様へのリンクがエラー内容説明にしかないのが気になりました。
末尾に参考文献としてAzure Face API仕様へのリンクを追加するか、APIの説明のTopにリンクを追加するなど仕様の読者の目につきやすいところにリンクがあると分かりやすいと思いました。

2021-03-03 08:04 UTC, tatsuyaagawa commented on doc/api/api.html
>  <meta charset="UTF-8">
確かにソースコードとして管理するのは微妙ですね
ただhtmlのプレビュー目的で必要なのかな

2021-03-03 08:23 UTC, tatsuyaagawa requested changes
タイポだけ

2021-03-03 08:23 UTC, tatsuyaagawa commented on doc/api/api.adoc
> +|mean(Ojbect)
```suggestion
|mean(Object)
```

2021-03-04 02:43 UTC, nishikawa1114 commented on doc/api/api.html
>  <meta charset="UTF-8">
HTMLプレビューのリンクをプルリクに貼るために、HTMLファイルもgithub上にある必要があるためpushしていました。
成果物管理として確かに不要なものですね。
今後どうするかは相談するとし、今回のプルリクでは今のまま(htmlもpushしてプレビューリンクをプルリクに貼る)の方式で進めさせてください。

2021-03-04 02:49 UTC, nishikawa1114 commented
以下の修正を行いました。
- レスポンスの型名修正
- レスポンス説明文の修正
- レスポンスサンプルの１人の場合のサンプル削除
- 参考文献の項目を追加
- 誤字修正

[API仕様書プレビュー](http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/api/doc/api/api.html)

確認お願いします。

2021-03-04 02:53 UTC, hiroshinhnakamura commented on doc/api/api.adoc
> +|total(nubmer)
タイポ: number

2021-03-04 04:05 UTC, yutsunom commented on doc/api/api.adoc
> +** 感情の強さ。[0,1]の間の数値。
両方だと思います。
Face API では桁数が定義されていないこと、実測上3桁であること、このAPI側としてもFace API の仕様に合わせるので有効桁数を定義しないこと（とするなら）が書かれていればいいかと

2021-03-04 04:38 UTC, iwanam approved these changes

2021-03-04 04:49 UTC, nishikawa1114 commented
以下の修正を行いました。
- 感情値の有効桁数について明記
  - 平均値では計算過程で無限小数になる可能性を考慮して３桁で丸める
  - FaceAPIからの返却値はそのまま利用するため有効桁数定義しない
- 誤字修正 

確認お願いします。
[API仕様書プレビュー](http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/api/doc/api/api.html)

2021-03-04 04:51 UTC, hiroshinhnakamura approved these changes

2021-03-04 04:52 UTC, yutsunom approved these changes

2021-03-04 04:55 UTC, tatsuyaagawa approved these changes

2021-03-04 05:06 UTC, merged