クラス図、シーケンス図を作成
nishikawa1114/FaceEmotionSystem pull request #2
Opened 2020-11-06 02:41 UTC by nishikawa1114

クラス図・シーケンス図を作成しました。
確認お願いします。

- 機能仕様書(ユースケース・画面仕様)
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/main/usecase/usecaseDescription.html

- クラス図
![Face Emotion](https://user-images.githubusercontent.com/69957397/98317805-8ce82b00-2020-11eb-85fd-b48256062691.png)

- シーケンス図 UC01
![UC01 画像を表示する](https://user-images.githubusercontent.com/69957397/98317814-940f3900-2020-11eb-9ee6-3f27423e500e.png)

- シーケンス図 UC02
![UC02 画像を分析する](https://user-images.githubusercontent.com/69957397/98317824-983b5680-2020-11eb-8c83-25981619ae63.png)

2020-11-06 04:56 UTC, msebata requested changes

2020-11-06 04:56 UTC, msebata commented on uml/classDiag.pu
> +    画像が存在するか確認する()
存在確認だけしてここでは取得はしないのでしょうか？
画像を取得する()がどこかに必要そうですが。 
(あと、個人的には存在しないケースは、画像を取得する()の例外として扱いたい)
画像を取得する()を追加する場合、どのクラスの責務とするかは別途考えてください。

2020-11-06 04:56 UTC, msebata commented on uml/classDiag.pu
> +class 分析結果画面 {
画面は基本的に、表示や見た目、簡単な入力値のチェックにとどめたほうがいいです。
また、FaceAPIなどの固有の外部APIや外部モジュールに直接依存するのもやめたほうがいいです。
一般的には、業務ロジック(ここでは画像分析処理)を別クラスにしたほうが結合度が下がり、変更容易性とテスタビリティが上がります。

2020-11-06 04:56 UTC, msebata commented on uml/classDiag.pu
> +class 画像を表示 {
画像を表示は動作なのでクラスというよりメソッド。表示自体はホーム画面の責務なのでは？

2020-11-06 06:06 UTC, nishikawa1114 commented on uml/classDiag.pu
> +    画像が存在するか確認する()
今回画像はクラウド上に存在している想定なので、画像の表示や分析するときもURLで指定してやり取りするつもりです。その場合、画像を取得するという工程は存在しておらず、URLを画像情報クラスが保持しておけば画像を持っていると同じ状態であると考えていました。(なので画像を取得する()メソッドはつくっていませんでした)

画像を取得する()というのは、画像情報クラスにデータをセットする部分も画像の取得に含めるべきで、それを行うメソッドは別途必要ということでしょうか？

2020-11-06 06:17 UTC, nishikawa1114 commented on uml/classDiag.pu
> +class 画像を表示 {
画像を表示クラスは、Reactのコンポーネントとして、画像領域の表示は別のコンポーネントで実装しようと考えてクラス図では別のクラスとして扱っていました。
ホーム画面から画像表示のコンポーネントを呼び出して描画するイメージだったのでこのような図になっていますが、ホーム画面クラスの機能として設計すべきでしょうか？

2020-11-06 07:14 UTC, msebata commented on uml/classDiag.pu
> +class 画像を表示 {
なるほど、Reactはよく知りませんが、再利用可能な画面の部品(コンポーネント )ということでしょうか。
であればこれでも良いですが、クラスの名前は名詞にしたほうがいいです。
例えば、、画像表示コンポーネント？ (適当)

2020-11-06 07:19 UTC, msebata commented on uml/classDiag.pu
> +    画像が存在するか確認する()
理解しました。 そういう設計なら必要ありません。

2020-11-06 08:01 UTC, nishikawa1114 commented
本日、以下の変更を実施しました。
確認お願いします。

- 分析クラスを追加。分析結果画面から分析機能を削除。FaceAPIとのやり取りを画像分析クラスが担うように変更

- 「画像を表示」クラスを「画像表示領域」クラスに名称変更

クラス図
![Face Emotion](https://user-images.githubusercontent.com/69957397/98340723-292a2600-2051-11eb-9693-b04bc5d2eda4.png)

シーケンス図UC01
![UC01 画像を表示する](https://user-images.githubusercontent.com/69957397/98340826-4eb72f80-2051-11eb-8544-d044520998bf.png)


シーケンス図UC02
![UC02 画像を分析する](https://user-images.githubusercontent.com/69957397/98340802-45c65e00-2051-11eb-8159-f0af0c8f99fa.png)

2020-11-06 09:30 UTC, iwanam commented
最初にみたときよりぐっとクラス図っぽくなりましたねぇ。
Viewのクラス図はむずかすぃ
ちなみにFaceAPIがクラスではなく、ただ外部のAPIなのであればアクターで記述するのがいいですね。
逆にFaceAPIを呼ぶための何かクラスを作るというのであれば、クラス図に出てこないのはなぜだろうってなります。
シーケンス図で矢印がひかれている箱同士は関連があるはずだからね。

2020-11-09 05:54 UTC, hiroshinhnakamura commented on uml/classDiag.pu
> +    エラー画面を表示する()
エラーの内容に基づいて画面の表示内容を変えるならば、メンバー変数や引数でエラーコードやエラーメッセージを指定できないといけないのでは？

2020-11-09 06:03 UTC, yutsunom requested changes

2020-11-09 06:03 UTC, yutsunom commented on uml/classDiag.pu
> +class 画像表示領域 {
props, state はないでしょうか？

2020-11-09 06:03 UTC, yutsunom commented on uml/classDiag.pu
> +class ホーム画面 {
React でしたら、
    入力されたURL
    画像情報のリスト
    選択された画像データ
は props, state でしょうか？

クラス図に出てこない要素でしたら、実装時は目安にするものは何かなと思いました。

2020-11-09 06:03 UTC, yutsunom commented on uml/classDiag.pu
> +class 分析結果画面 {
ホーム画面で、画像表示領域とクラス分けをしたのなら、分析結果画面もいくつかに分かれそうな気もしますが、不要でしょうか

2020-11-09 06:03 UTC, yutsunom commented on uml/classDiag.pu
> +class 画像分析 {
個人的には、入力チェッククラスと合わせて、Util クラスでもいいかな、と思いました

2020-11-09 07:55 UTC, tatsuyaagawa commented
阿川分は先週口頭で確認済みなので、他の方の指摘対応をお願いします

2020-11-10 01:46 UTC, nishikawa1114 commented on uml/classDiag.pu
> +class ホーム画面 {
>React でしたら、
入力されたURL
画像情報のリスト
選択された画像データ
は props, state でしょうか？

すみません。ちょっと理解できていないのですが、propsかstateなのかをクラス図にも明記したほうが良いということですか？
propsは呼び出し時の引数のようなものと考えているのですが、クラス図の場合はメンバ変数として記載するものなのでしょうか？

2020-11-10 01:48 UTC, nishikawa1114 commented on uml/classDiag.pu
> +class 画像表示領域 {
こちらも意図が理解できていないのですが、必要なpropsやstateがあるはずということでしょうか？

2020-11-10 05:51 UTC, yutsunom commented on uml/classDiag.pu
> +class ホーム画面 {
Props, State はクラス図、シーケンス図では表現しにくいから出してないのかな、と思っていますが、もしそういう意図でしたら、どこかで書くつもりでしたか？
という質問になります。

2020-11-10 06:43 UTC, nishikawa1114 commented on uml/classDiag.pu
> +class ホーム画面 {
stateはメンバ変数っぽいと考えていたので、クラス図ではメンバ変数として、
- 入力されたURL
- 画像情報のリスト
- 選択された画像データ

はstateのつもりで書いています。

propsは明確にどこかに書いておくことが考えられていませんでした。
(メソッドの引数として、必要になりそうな情報を書いておくことで実装時の参考程度になるか、くらいで考えていました。)

2020-11-11 01:59 UTC, nishikawa1114 commented
以下の変更を行いました。

○クラス図

- エラー画面の表示を引数でメッセージを指定できるよう変更

- 分析結果画面を画像、グラフ、表の表示を別クラスに分割

- 分析する機能を入力チェック機能と統合してUtilクラスに変更


現在のクラス図、シーケンス図を載せます。
○クラス図
![Face Emotion](https://user-images.githubusercontent.com/69957397/98755625-53426600-240c-11eb-847b-0c1771a19b7d.png)

○シーケンス図UC01
![UC01 画像を表示する](https://user-images.githubusercontent.com/69957397/98755752-8be23f80-240c-11eb-93be-4dafdafe61a7.png)

○シーケンス図UC02
![UC02 画像を分析する](https://user-images.githubusercontent.com/69957397/98755704-710fcb00-240c-11eb-8f75-5e92c933b667.png)

2020-11-11 02:23 UTC, msebata commented on uml/classDiag.pu
> +class 画像分析 {
あくまで私の個人的な意見ですが、、
「画像の分析」はこのシステムの大事な業務ロジックなので、ユーティリティ＝いろんな場所で使える状態を持たない便便利なstaticクラス とは違うかな、と思います。
別にオブジェクト指向原理主義者のごとくユーティリティクラス絶対反対というわけではありません。簡単な入力値チェックなどは業務が変わっても使えるのでユーティリティでいいと思います。
この辺、人によって考え方が違うし正解はないので、そんな考え方もあるな、程度に思っていただければ。
画像分析を業務ロジックではなく使いまわし可能な部品と定義するなら、宇都宮さんの意見も正しいです。

2020-11-11 02:51 UTC, nishikawa1114 commented on uml/classDiag.pu
> +class 画像分析 {
なるほど。
そのあたりちゃんと考えられていませんでした。

お二人の意見を参考にして、
画像の分析はシステムのメイン機能ということもあるので、今回は専用のクラスとして設計したいと思います。

2020-11-17 00:40 UTC, tatsuyaagawa approved these changes

2020-11-17 07:32 UTC, nishikawa1114 commented
以下の修正を実施しました
確認お願いします。

- 分析機能をUtilクラスから独立のクラスへ分割
- クラス図のメンバにState,Propsの記述を追加

クラス図画像
![Face Emotion](https://user-images.githubusercontent.com/69957397/99359366-5056e200-28f2-11eb-8a45-4a92b3068318.png)

2020-11-17 07:40 UTC, hiroshinhnakamura approved these changes

2020-11-17 07:44 UTC, msebata approved these changes

2020-11-19 00:30 UTC, tatsuyaagawa commented
@yutsunom 
すいません。次の工程に進みたいので現時点で一旦マージします。
指摘がありましたら、コメントをお願いします。ただ対応は12月以降に追加実施とさせてください。

2020-11-19 08:59 UTC, yutsunom commented on uml/classDiag.pu
> +class 画像分析 {
了解です

2020-11-20 04:26 UTC, yutsunom approved these changes
クラス図はよさげ
シーケンスは見切れてないとこあります。やってみて修正必要ならまた教えてください・・

2020-11-25 08:11 UTC, merged