【OJT後半課題3】平均値を表示する機能の追加 ソースコード・単体テスト作成
nishikawa1114/FaceEmotionSystem pull request #21
Opened 2021-03-10 04:52 UTC by nishikawa1114

**【OJT後半課題3】平均値を表示する機能の追加 ソースコード・単体テスト作成**

OJT課題で作成している感情分析アプリケーションに画像に写る人の感情の平均値を表示する機能を追加しました。
実装方法、コードの書き方等ご指摘お願いします。

- サーバーサイドの変更
レスポンスに感情の平均値のデータを含めるように変更しています

- フロントサイドの変更
分析結果が複数人の場合、平均値を表示するように変更しています(分析結果が1人の場合は平均値は表示しない)

- カバレッジは以下のファイルからご確認ください
  - フロントサイド
[coverage.zip](https://github.com/nishikawa1114/FaceEmotionSystem/files/6113204/coverage.zip)
  - サーバーサイド
[coverage.zip](https://github.com/nishikawa1114/FaceEmotionSystem/files/6113206/coverage.zip)

- 実行結果スクショ
- フロントサイド
  - ホーム
  ![image](https://user-images.githubusercontent.com/69957397/110577712-8cb29480-81a6-11eb-82e3-0ea5fecfd9be.png)

  - 分析結果
    - 一人
    ![image](https://user-images.githubusercontent.com/69957397/110578221-aa342e00-81a7-11eb-985a-463f72c5b56f.png)

    - 複数人
    ![image](https://user-images.githubusercontent.com/69957397/110578182-8f61b980-81a7-11eb-9f89-84df5e8912e7.png)

2021-03-10 05:13 UTC, tatsuyaagawa commented on doc/functional_specifications/function_specification.html
> -<div class="paragraph">
adoc, htmlの修正は今回のレビュー対象じゃないと思うので、ブランチから消しておいてください

2021-03-10 09:13 UTC, msebata requested changes

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ResponseFactory.java
> +		// �e����l�̕��ϒl�̌v�Z
平均値の入れ物であるmeanEmotionに一時的に平均値以外(合計)を入れるのが微妙に見えるけど、変数増えちゃうからこれが一番楽か。

ちなみに以下のような取り方もあります。(上のほうがループ1回しか回してないから速いかもしれないけど、下のほうが今風かも)

```java
double avgEmotion = Arrays.stream(data).mapToDouble(d -> r.getEmotion()).average().orElse(0);
double avgContempt = Arrays.stream(data).mapToDouble(d -> r.getContempt()).average().orElse(0);
・・・
```

もっと良い方法もあるかも。

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ResponseFactory.java
> +	public static double floorDecimal(double number, int digit) {
ここもパッケージプライベート推奨。

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ResponseFactory.java
> +		int temp = (int) (number * Math.pow(10, digit-1));
`Math.pow(10, digit-1)` は2回出てきてるので変数に入れましょう。

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ResponseFactory.java
> +	public static double floorDecimal(double number, int digit) {
あと、このクラス内でしか使わないなら、digitは4固定でもいいかも。(そのほうが引数が減ってテスト少なくて済むし)

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +	void testFloorDecimal1() {
テストメソッド名は、なるべくどんなテストかわかる名前が望ましいです。(コメントはテスト結果に出ないから)

英語だと
`testFloorDecimal_floorBy4_lowerThan5` とか？ (自信ない)

ちなみにメソッド名には日本語も使えます。(個人的には好きだけど嫌がる人もいる)
`testFloorDecimal_小数第4位切り捨て_5未満()`

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +		Emotion emotion1 = new Emotion();
（参考までに）
テストの準備で同じような処理が繰り返される場合、ヘルパーメソッドを作って、見やすくする手もあります。
例えば、、
`FaceAttributes createFaceAttributes(anger, contempt, disgust, fear, happiness, neutral, sadness, surprise) { }`
のようにEmotionとFaceAttributesを初期化するメソッドを用意するとか。

こうすると、だいぶ見通しが良くなります。

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/MeanFaceAttributes.java
> +public class MeanFaceAttributes {
このクラスの意義が良くわからないのですが。 
ResponseData に直接 faceAttributes をセットしてもいいような。

2021-03-10 09:13 UTC, msebata commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/response/ResponseFactory.java
> +	public static Emotion calcMeanEmotion(ResultData[] data) {
テストしたいために公開するなら、publicでなくパッケージプライベート(何もつけない)で十分だと思います。

2021-03-11 00:11 UTC, tatsuyaagawa requested changes

2021-03-11 00:11 UTC, tatsuyaagawa commented on src/my-app/src/AnalyzeDetail.tsx
> +        document.addEventListener('DOMContentLoaded',  () => {
ここはなんで追加したんですか？

2021-03-11 00:11 UTC, tatsuyaagawa commented on src/my-app/src/AnalyzeResult.tsx
> +                            Array(this.state.responseData.person.slice(0, MAX_ANALYSIS_DISPLAY_LENGTH).length).fill(this.state.responseData.person.slice(0, MAX_ANALYSIS_DISPLAY_LENGTH)).map((value, i
現状二回同じ計算をしていますし、よみづらいのでthis.state.responseData.person.slice(0, MAX_ANALYSIS_DISPLAY_LENGTH)はrender関数の2行目あたりで計算しておくとほうが良いかなと思いました

あとArrayにfillでresponseDataを突っ込んでるところが気になったので、以下のように修正できないか検討してみてください

現状のコードだと
①必要な要素数のArrayをつくる
②Arrayの各要素にresponseDataをArrayのまま必要数入れる
③②から順番にArrayを取り出し、そのArrayの中で使うものだけをさらに取り出して描画する

となっていると思うので、下記のように修正すると良いと思います

①responseDataのArrayから必要数取り出す
②①のArrayから順番にデータを取り出し描画する

2021-03-11 00:11 UTC, tatsuyaagawa commented on src/my-app/src/Analyzer.ts
> +        // const subscriptionKey = String(process.env.REACT_APP_FACE_SUBSCRIPTION_KEY);
ここのコメントは自前のAPIでなく、Azureを直接たたきたいときに必要だから残していると思うので、その旨もコメントとして残しておくと良いと思います

2021-03-11 01:00 UTC, nishikawa1114 commented on src/my-app/src/AnalyzeDetail.tsx
> +        document.addEventListener('DOMContentLoaded',  () => {
@tatsuyaagawa

単体テストを行ったときに、getcontext()がnullですというエラーが発生したので、
その null対策のために追加しました。

2021-03-11 01:21 UTC, nishikawa1114 commented on server/FaceEmotionAnalyzerAPI/src/main/java/com/face/model/MeanFaceAttributes.java
> +public class MeanFaceAttributes {
@msebata

レスポンスのJSONを

{
　"total": 2,
　"mean": { 
　　"faceAttributes": {
　　　"emotion": {
　　　　"anger": 0.0,
　　　　"contempt": 0.001,
　　　　"disgust": 0.0,
　　　　"fear": 0.0,
　　　　"happiness": 0.0,
　　　　"neutral": 0.97,
　　　　"sadness": 0.028,
　　　　"surprise": 0.0
	　}
	}
　},
・・・

の形にする仕様としており、ResponseDataのメンバにfaceAttributesをセットしてしまうとmeanの直下にemotionが入ってしまうと考えたのでFaceAttributesのみをメンバに持つクラスを用意しました。
(今考えるとmean直下に入っても困ることはないのですが、仕様書に合わせる目的です。)

2021-03-11 06:35 UTC, nishikawa1114 commented
以下の点を修正しました。
-  サーバーサイド
   - floorDecimai()メソッドを小数第4位以下を固定で切り捨てる関数へと変更。→floorDecimalPlace4() 
   - 上記に伴い、切り捨て桁数に関するテストの削除
   - テストメソッド名の変更
   - 複数出てくる処理(Emotionの初期化)の関数化
   - 関数のアクセスをprivateに変更
   - 平均値の計算処理の変更
- フロントサイド
  - 分析結果表示処理のループ処理の修正
  - コメント追加

確認お願いします。

2021-03-11 06:37 UTC, ntabei commented on src/my-app/src/types.ts
> +export interface MeanfaceAttributes {
細かいところなのですが、faceの「f」が大文字じゃないのが気になりました（FaceAttributesというinterfaceがあるのに）

2021-03-11 06:55 UTC, tatsuyaagawa commented on src/my-app/src/AnalyzeResult.tsx
> +                            resultData10.map((value, i: number) => {
👍

2021-03-11 07:06 UTC, tmatsumura requested changes

2021-03-11 07:06 UTC, tmatsumura commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +		assertThat(result.getAnger()).isEqualTo(mean.getFaceAttributes().getEmotion().getAnger());
`mean.getFaceAttributes().getEmotion()`までを`meanEmotion`みたいな変数に入れて、以降それを使った方が見やすいと思います

2021-03-11 07:06 UTC, tmatsumura commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +		assertThat(result.getMean().getFaceAttributes().getEmotion().getAnger()).isEqualTo(responseData.getMean().getFaceAttributes().getEmotion().getAnger());
これもレスポンス(`result.getMean().getFaceAttributes().getEmotion()`)と期待値(`responseData.getMean().getFaceAttributes().getEmotion()`)を何か変数に入れた方がいいです

2021-03-11 07:06 UTC, tmatsumura commented on server/FaceEmotionAnalyzerAPI/src/test/java/com/face/response/ResponseFactoryTest.java
> +		assertThat(result.getMean().getFaceAttributes().getEmotion().getAnger()).isEqualTo(responseData.getMean().getFaceAttributes().getEmotion().getAnger());
あと、`responseData`の方は全部`getAnger`になってます

2021-03-11 07:45 UTC, nishikawa1114 commented
以下の修正を行いました。
 - サーバーサイド
   - 共通部分を変数化
   - 不要なコメントの削除
 - フロントサイド
   - クラス名を修正

確認お願いします。

2021-03-11 08:30 UTC, ntabei approved these changes

2021-03-11 08:42 UTC, tmatsumura approved these changes

2021-03-11 23:52 UTC, msebata approved these changes

2021-03-12 00:45 UTC, tatsuyaagawa approved these changes

2021-03-15 05:16 UTC, merged