UC01「画像を表示する」の実装
nishikawa1114/FaceEmotionSystem pull request #5
Opened 2020-11-27 01:29 UTC by nishikawa1114

UC01「画像を表示する」の機能を実装しました。

- 仕様書の内容を満たしているか
- 修正したほうが良い箇所がないか

などのソースコードの確認お願いします。

 **ホーム画面のキャプチャ**
![image](https://user-images.githubusercontent.com/69957397/100400424-dbc23700-3099-11eb-9b1c-926d724424ec.png)

 **エラー画面のキャプチャ**
![image](https://user-images.githubusercontent.com/69957397/100400442-ea105300-3099-11eb-8e0e-f2ae0d52bee7.png)

 **機能仕様書**
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/main/usecase/usecaseDescription.html

 **クラス図** 
![Face Emotion](https://user-images.githubusercontent.com/69957397/100400013-59854300-3098-11eb-988c-02fb9a05897b.png)

 **シーケンス図UC01** 
![UC01 画像を表示する](https://user-images.githubusercontent.com/69957397/100400005-512d0800-3098-11eb-977c-7155b577fe61.png)

2020-11-27 07:11 UTC, tatsuyaagawa reviewed
細かい話が多くなってしまいましたが確認お願いします

2020-11-27 07:11 UTC, tatsuyaagawa commented on my-app/src/Error.tsx
> +        if (this.props.errorId == 1) {
```suggestion
        if (this.props.errorId === 1) {
```
基本javascriptでは `==` を使う場面はないと思って良いです

2020-11-27 07:11 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +    const checkedImage = this.state.checkedImage;
```suggestion
   const {images, checkedImage} = this.state;
```

2020-11-27 07:11 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +    if (exit) { // 画像が存在する場合
例外的なパターンをチェックして先にreturnするようにした方が見通しが良いことが多いです
https://qiita.com/Nossa/items/3fb1f1e4c429cacd3365#%E6%97%A9%E6%9C%9F%E3%83%AA%E3%82%BF%E3%83%BC%E3%83%B3%E3%82%84%E3%82%AC%E3%83%BC%E3%83%89%E7%AF%80%E3%82%92%E4%BD%BF%E3%81%86

```
if (!exit) {
  this.setState({
        errorId: 1,
        isError: true,
      })
  return;
}

// 画僧が存在する場合
this.setState({
        images: images.concat({
          id: images.length + 1,
          url: this.state.inputUrl,
        }),

(略)
```

2020-11-27 07:11 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +        <div>
分析画面も増えると複雑になりそうなので、画像表示画面の箇所もrender関数の外に出しておきたいです

2020-11-27 07:11 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +    }
（余裕があったらでいいです）for文で書いているところはArray.prototype.filter使って書き直してみてください

2020-11-27 07:11 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +  private handleClick = (i: number) => {
仕様的には複数選択はできてOKなんでしたっけ？

2020-11-30 00:16 UTC, tatsuyaagawa commented
.gitgnoreも入れといてくださいー

2020-12-03 02:11 UTC, msebata requested changes

2020-12-03 02:11 UTC, msebata commented on my-app/src/AnalysResult.tsx
> +interface emotion {
class, interface名の命名規則を揃えたほうがいいと思います。(Image, Emotionとか)
TypeScriptはパスカルケースが普通なのかな？

2020-12-03 02:11 UTC, msebata commented on my-app/src/AnalysResult.tsx
> +interface analyseProps {
「分析」なら綴りは analysis では？ 動詞なら analyze
ここだけでなく全体的に見直しをお願いします。

2020-12-03 02:11 UTC, msebata commented on my-app/src/AnalysResult.tsx
> +    private analyseImage = async (str: string) => {
綴り analyze

2020-12-03 02:11 UTC, msebata commented on my-app/src/Analyser.ts
> +    public static analyse(str: string) {
変数名strは 、もう少し意味のある名前を付けたほうが分かりやすいです。
ここ以外も結構変数名が適当なので、全体的に見直しをお願いします。

2020-12-03 02:11 UTC, msebata commented on my-app/src/Analyser.ts
> +export class Analyser {
Analyzer

2020-12-03 02:11 UTC, msebata commented on my-app/src/index.tsx
> +  errorId: number; // 1:画像が存在しない, 2:分析結果が取得できない, 0:エラーなし
それぞれの箇所で好きな値を代入できてしまうため、定数や型(enumとかunion？)で定義したほうがいいです。
displayIdも同様。
TypeScriptとのenumとかunionはよく分からないので、アドバイスできませんが。。
最低限、以下のように定数を定義して、代入はそれを使うようにしたほうがいいです。
`const  ERROR_IMAGE_NOT_EXISTS : number = 1;`

2020-12-03 02:11 UTC, msebata commented on my-app/src/Util.ts
> +    static exitImage(str: string) {
綴り exist
あと細かいですが、existは自動詞のため、 exist○○という書き方は普通しません。
なので `image_exists` がいいかな。
(参考) https://qiita.com/yskszk/items/5a7f99c974773f03a82a#%E5%AD%98%E5%9C%A8%E3%81%99%E3%82%8B%E3%81%8B

2020-12-03 02:11 UTC, msebata commented on my-app/src/Graph.tsx
> +interface CraphProps {
Graph ？

2020-12-03 02:11 UTC, msebata commented on my-app/src/AnalysResult.tsx
> +interface Image {
idとurlを持つ interface Image がいろいろなところで定義されているですが、みんな違うのでしょうか？
1つ定義すればいい気がしますが。(よく確認してないので間違ってたらごめん)

2020-12-03 02:11 UTC, msebata commented on my-app/src/ImageArea.tsx
> +    checkedImage: Array<boolean>
配列なので基本的には複数形のほうがいいです。(「基本的には」といったのは、世の中そうじゃない実装もたくさんあるので)

2020-12-03 02:11 UTC, msebata commented on my-app/src/Table.tsx
> +interface emotion {
emotionも何回も定義されているような。 1つでいい気がします。
(実装するクラスと同じファイルにないといけないとかいう、言語上の縛りはないですよね？)

2020-12-04 00:11 UTC, tatsuyaagawa requested changes

2020-12-04 00:11 UTC, tatsuyaagawa commented on my-app/src/AnalysResult.tsx
> +                return;
Acureへのアクセスでエラーが返ってきたときもここに入る？

2020-12-04 00:11 UTC, tatsuyaagawa commented on my-app/src/Analyser.ts
> +        let imageUrl = str;
変更されることのない変数はconstのほうが良いです

2020-12-04 00:11 UTC, tatsuyaagawa commented on my-app/src/Analyser.ts
> +        const query_params = new URLSearchParams(params);
このあたりの変数名は
params→queryParams 
query_params→queryString とか？

2020-12-04 00:11 UTC, tatsuyaagawa commented on my-app/src/Analyser.ts
> +                // 分析結果が空の場合
分析結果が空になる場合ってどういうときでしょうか？
そういう情報をコメントに書いておくと良いと思います

2020-12-04 00:11 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +  errorId: number; // 1:画像が存在しない, 2:分析結果が取得できない, 0:エラーなし
enumでerrorIdの取りうる値を定義すると良いかなと思います
https://typescript-jp.gitbook.io/deep-dive/type-system/enums

2020-12-04 02:35 UTC, tatsuyaagawa commented on my-app/src/index.tsx
> +    this.state.checkedImage.filter((value, index) => {
すいません。最初にレビューしたときははcountを計算してただけだったのでfilterでtrueだけにすればいいと思ったのですが、checkedId も必要なのであれば今回はforEachで良いと思います
（checkedImageがbooleanの配列になっていて扱いにくくなってるので、check済みのの配列になってると扱いやすいのかなと思いました）

2020-12-07 01:54 UTC, tatsuyaagawa commented on my-app/src/Analyser.ts
> +'use strict';
必要ないので削除しておいてください

2020-12-07 01:54 UTC, tatsuyaagawa commented on my-app/src/Table.tsx
> +                        <tr >
```suggestion
                        <tr  key={key>
```
なんかエラーが出てたので

2020-12-07 02:11 UTC, skashiyama requested changes
差分が1.7万行あって、おそらく無駄なファイル・行が含まれていると思うので整理をお願いします

2020-12-07 02:18 UTC, tatsuyaagawa commented
@skashiyama 
my-app/package-lock.json が1.6万行以上あるようです。
こちらは必要なファイルですがレビューしていただかなくて大丈夫です。

伝えられておらずすみませんが、ts, tsx, css, htmlファイルについてレビューをお願いします

2020-12-07 05:35 UTC, skashiyama requested changes

2020-12-07 05:35 UTC, skashiyama commented on my-app/src/Error.tsx
> +            errorMessage = '予期しないエラー'
エラーメッセージの書き方がここだけそろってないです。

2020-12-07 05:35 UTC, skashiyama commented on my-app/src/Home.tsx
> +// interface HomeState {
ただ、コメントアウトするのではなくコメントアウトした理由を追記しておいた方が後々楽です。

2020-12-07 06:00 UTC, nishikawa1114 commented on my-app/src/Home.tsx
> +// interface HomeState {
修正中に不必要になったのでとりあえずコメントアウトしていた部分でしたので、削除します。
(こういう判断もコメントアウトの理由があれば確認しやすいですね。)

2020-12-07 06:43 UTC, tatsuyaagawa approved these changes

2020-12-07 23:32 UTC, msebata approved these changes

2020-12-08 01:48 UTC, skashiyama approved these changes

2020-12-08 06:17 UTC, merged