UC01「画像を表示する」,UC02「画像を分析する」 単体テストコード作成
nishikawa1114/FaceEmotionSystem pull request #6
Opened 2020-12-09 01:27 UTC by nishikawa1114

OJT課題で作成しているwebアプリケーションの単体テストコードを作成しました。
開発環境はReact / TypeScript、テストにはjestを利用しています。
ファイル名の末尾が「.test.tsx」「.test.ts」となっているのがテストコードとなります。

テストケースの漏れや修正点などについて確認お願いします。

以下のクラスはReactコンポーネントでありhtmlを返す機能のため、出力されるhtmlコードを見て表示の確認を行っています。

- index.tsx
- Home.tsx
- ImageArea.tsx
- ImageInfo.tsx
- AnalyzeResult.tsx
- Error.tsx
- Table.tsx

※index.tsx内のフォーム入力やボタン押下などで実行される○○handle()のような関数のテストは単体テストでは実施しません。統合テストにて正しく動作するか確認します。

 下記のクラスはライブラリを呼び出しているだけのため単体テストは実施していません。統合テストにて正しく表示されれていることを確認いたします。
- Graph.tsx

**カバレッジ**
index.tsxのみ低い数字となっていますが、ボタン操作、画面遷移などに関する関数のテストを今回実施していないためです。
それらに関するテストは統合テストにて確認する予定です。

File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------|---------|----------|---------|---------|-----------------------------------------------
All files          |   82.78 |    67.57 |    71.7 |   81.22 |                                               
 AnalyzeResult.tsx |   89.29 |       80 |    87.5 |   86.96 | 49-50,71                                      
 Analyzer.ts       |   88.89 |      100 |      80 |   88.24 | 42-43                                         
 Error.tsx         |     100 |      100 |     100 |     100 |                                               
 Graph.tsx         |     100 |      100 |     100 |     100 | 
 Home.tsx          |   92.31 |       50 |   66.67 |      90 | 53
 ImageArea.tsx     |   93.75 |      100 |      80 |   91.67 | 20
 ImageInfo.tsx     |     100 |      100 |     100 |     100 |                                               
 Table.tsx         |     100 |      100 |     100 |     100 |                                               
 Util.ts           |    87.5 |      100 |   66.67 |   86.67 | 19,22
 index.css         |     100 |      100 |     100 |     100 | 
 index.tsx         |   55.74 |    44.44 |   30.77 |   56.14 | 39-52,65,70-72,77-80,89-90,97,111-113,132-144

**機能仕様書**
http://htmlpreview.github.io/?https://github.com/nishikawa1114/FaceEmotionSystem/blob/mt/usecase/usecaseDescription.html

**クラス図**
https://github.com/nishikawa1114/FaceEmotionSystem/blob/mt/out/uml/classDiag/Face%20Emotion.png

**シーケンス図**
UC01 画像を表示する
https://github.com/nishikawa1114/FaceEmotionSystem/blob/mt/out/uml/seqDiag01/UC01%20%E7%94%BB%E5%83%8F%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.png
UC02 画像を分析する
https://github.com/nishikawa1114/FaceEmotionSystem/blob/mt/out/uml/seqDiag02/UC02%20%E7%94%BB%E5%83%8F%E3%82%92%E5%88%86%E6%9E%90%E3%81%99%E3%82%8B.png

2020-12-09 01:53 UTC, tatsuyaagawa commented
@nishikawa1114 
コンフリクトしてるので直しましょう
Home.tsxとindex.tsxについて、昨日マージした変更と違う修正が入っているみたいです

2020-12-09 02:10 UTC, nishikawa1114 commented
コンフリクトを修正しました。

2020-12-09 02:24 UTC, tatsuyaagawa commented on my-app/src/Home.tsx
> +    const isInputUrl: boolean = Util.isInput(this.props.inputUrl); // URLの入力済確認
このファイルとindex.htmlに差分が出てるのは必要な修正でしょうか？
（MTでエラーになったとかで結果修正した部分？）

2020-12-09 02:38 UTC, nishikawa1114 commented on my-app/src/Home.tsx
> +    const isInputUrl: boolean = Util.isInput(this.props.inputUrl); // URLの入力済確認
index.tsxでしょうか？(index.htmlは変更されていないと思うのですが)
index.tsxの変更であれば単体テストを実施する際に、スナップショットに内容を出力するために必要だったために変更しました。

Home.tsxはソースコードをリファクタリングした時の変更点になります。

2020-12-09 02:44 UTC, tatsuyaagawa commented on my-app/src/Home.tsx
> +    const isInputUrl: boolean = Util.isInput(this.props.inputUrl); // URLの入力済確認
了解です（index.tsxでしたね・・）

2020-12-10 00:46 UTC, tatsuyaagawa requested changes

2020-12-10 00:46 UTC, tatsuyaagawa commented on my-app/src/__tests__/ImageInfo.test.tsx
> +import { ImageInfo } from "../ImageInfo";
getDate, getNameのテストも追加お願いします

2020-12-10 00:46 UTC, tatsuyaagawa commented on my-app/src/__tests__/Error.test.tsx
> +        expect(tree2).toMatchSnapshot();
`expect(JSON.stringify(tree.toJSON())).toContain("予期しないエラーが発生しました");`
表示だけしているところも簡単で良いので内容の確認をお願いします
snapshotにもありますが。
（参考までにこういったパラメータのテストやクリック時のテストはenzumeというライブラリを使うと簡単にできます。）
https://mae.chab.in/archives/60066

2020-12-10 02:11 UTC, iwanam requested changes
今は規模が小さいからあまりメリットを感じないかもだけど、必要に応じてdescribeからのitのほうがわかりやすくなるかも。
ちなみにtestとitが混じっているけど何か使い分けしている感じ？

2020-12-10 02:19 UTC, nishikawa1114 commented
@iwanam 
>ちなみにtestとitが混じっているけど何か使い分けしている感じ？

特に意図があったわけではないです。どちらでもできると聞いたので試したのがそのままでした。
今回はitに統一しようと思います。

2020-12-10 06:19 UTC, yutsunom approved these changes
カバレッジのhtmlを見せてください
すみませんが、1個1個のテスト見てる時間がないので、どの分岐を通したという見方をさせてほしいためです

2020-12-10 06:21 UTC, yutsunom requested changes
（すみませんApprove に押し間違いしてました）
カバレッジのhtmlを見せてください
すみませんが、1個1個のテスト見てる時間がないので、どの分岐を通したという見方をさせてほしいためです

2020-12-10 07:08 UTC, nishikawa1114 commented
@yutsunom 
カバレッジのhtmlファイルを追加しました。先頭のコメントから確認いただけます。

2020-12-10 07:45 UTC, iwanam approved these changes
勉強のためという理由は今の目的としては正しいっすね
実務の場合は、複数の書き方を混ぜると混乱するのでなるべく統一するほうがいいですけど、勉強中はいろいろ試すのも大事。
今回のように「自分はこう考えていた」と主張できるのは重要なのでこれからも主張を大事にしていってください（頑固とは違う

2020-12-10 08:41 UTC, yutsunom commented
> index.tsxのみ低い数字となっていますが、ボタン操作、画面遷移などに関する関数のテストを今回実施していないためです。
それらに関するテストは統合テストにて確認する予定です。

今回実施しなかった理由は何でしょうか？

2020-12-11 00:01 UTC, tatsuyaagawa requested changes
zipで渡したようなのでカバレッジのhtmlファイルは除外しておいてください(gitで管理したくないので)

2020-12-11 01:06 UTC, nishikawa1114 commented
@yutsunom 
>今回実施しなかった理由は何でしょうか？

- 今回使用したjestではボタン操作、画面遷移などのテストが難しい
- 統合テストを実施することでボタン操作や画面遷移の確認が充分にできると判断
- 時間的にすべてのテストを単体テストで実施することが難しい

等の理由によりコーチャーと相談の上、単体テストではボタン操作や画面遷移のテストを実施せず、
統合テストでの動作確認のみといたしました。

2020-12-11 05:06 UTC, tatsuyaagawa approved these changes

2020-12-16 01:50 UTC, yutsunom approved these changes

2020-12-23 00:54 UTC, merged